apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-episode3
  labels:
    app: backend
    episode: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      episode: "3"
  template:
    metadata:
      labels:
        app: backend
        episode: "3"
    spec:
      containers:
      - name: backend
        image: junaid757/episode-03_backend 
        ports:
        - containerPort: 5002
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-episode3
  labels:
    app: backend
    episode: "3"
spec:
  selector:
    app: backend
    episode: "3"
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
    nodePort: 30009
  type: NodePort
  