version: '3.9'
services:
  backend:
    build: ./backend
    container_name: ep4_backend_4.0
    environment:
      # Backend connects to MongoDB at mongo3:27017 inside the network
      MONGO_URI: "mongodb://mongo4:27017/mydb"
    ports:
      - "3012:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: ep4_frontend_4.0
    depends_on:
      - backend
    ports:
      - "8091:80"
    networks:
      - app-network

networks:
  app-network:
    external: true