apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-episode2
  labels:
    app: backend
    episode: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      episode: "2"
  template:
    metadata:
      labels:
        app: backend
        episode: "2"
    spec:
      containers:
      - name: backend
        image: junaid757/episode-02_backend  
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-episode2
  labels:
    app: backend
    episode: "2"
spec:
  selector:
    app: backend
    episode: "2"
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30008 
  type: NodePort
  
