apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-episode2
  labels:
    app: frontend
    episode: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      episode: "2"
  template:
    metadata:
      labels:
        app: frontend
        episode: "2"
    spec:
      containers:
      - name: frontend
        image: junaid757/episode-02_frontend  
        ports:
        - containerPort: 81
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-episode2
  labels:
    app: frontend
    episode: "2"
spec:
  selector:
    app: frontend
    episode: "2"
  ports:
  - protocol: TCP
    port: 81
    targetPort: 81
  type: LoadBalancer
