apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-episode1
  labels:
    app: backend
    episode: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      episode: "1"
  template:
    metadata:
      labels:
        app: backend
        episode: "1"
    spec:
      containers:
      - name: backend
        image: junaid757/episode-01_backend 
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-episode1
  labels:
    app: backend
    episode: "1"
spec:
  selector:
    app: backend
    episode: "1"
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007 
  type: NodePort
