apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-episode1
  labels:
    app: frontend
    episode: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      episode: "1"
  template:
    metadata:
      labels:
        app: frontend
        episode: "1"
    spec:
      containers:
      - name: frontend
        image: junaid757/episode-01_frontend
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-episode1
  labels:
    app: frontend
    episode: "1"
spec:
  selector:
    app: frontend
    episode: "1"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
